name: Process External PRs

on:
  pull_request_target: # Please read https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ before using
     types: [opened, ready_for_review, closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: reviewpls

  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }} # assign pull request author
          reviewers: andf-unaffiliated
          ready-comment: ":tada: Thanks for your Pull Request! We appreciate your help improving our documentation!<br><br>:memo: Please take a moment to check the following:<ul><li>Have you signed our contributor agreement? If not, look for a comment from **cockroach-teamcity** with instructions. We cannot review your submission until you've signed this agreement.</li><li>Does your submission adhere to our [Style Guide](https://github.com/cockroachdb/docs/blob/master/StyleGuide.md)? Please edit your PR to meet these guidelines if necessary: our docs follow our style guide to maintain consistency, readability, and clarity throughout.</li></ul><br>:writing_hand: We'll respond here as soon as we can. Thanks!"
          merged-comment: ":tada: We've merged your PR! Thanks again for helping to improve our documentation!"
